name: Gh-Pages

on:
  push:
    branches:
      - main
  
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'main'
      - run: flutter pub get
      - run: flutter create --platforms web .
      - run: flutter build web --release --base-href=/megalergik/ --web-renderer=canvaskit
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'build/web'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
   
      - name: Remove base tag from index.html
        run: sed -i '/<base href=".*">/d' ./build/web/index.html


      - uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          ITCH_GAME: megalergik
          ITCH_USER: nergnezor
          PACKAGE: build/web
          CHANNEL: html5

